maintainer/controllers/OverallController.php
<?php
/**
 * 卡券生成管理
 */

namespace maintainer\controllers;

use maintainer\components\LoginedController;

use common\models\Statistics;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use common\models\Seller;
use m35\thecsv\theCsv;

/**
 * CardController implements the CRUD actions for CardCouponsGrant model.
 */
class OverallController extends LoginedController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [];
    }


    /**c
     * Lists all CardCouponsGrant models.
     * @return mixed
     */
    public function actionIndex()
    {

        if (Yii::$app->request->isAjax) {
            $respon = array();
            $pageSize = Yii::$app->request->post('length', 10);
            $start = Yii::$app->request->post('start', 0);//偏移量
            $model = $this->_condition();

            $total = $model->count();
            $total_card = $model->sum('card_num');
            $total_active = $model->sum('active_num');
            $total_settle = $model->sum('settle_num');
            $total_ac = $total_card ? round(100 * $total_active / $total_card, 2) : 0;
            $total_se = $total_card ? round(100 * $total_settle / $total_card, 2) : 0;
            $s_text = '';
            $dataProvider = new ActiveDataProvider([
                'query' => $model->limit($pageSize)->offset($start),
                'pagination' => [
                    'pageSize' => $pageSize,
                    'page' => intval($start / $pageSize),
                    'totalCount' => $total
                ],
            ]);

            if ($data = $dataProvider->models) {

                foreach ($data as $item) {
                    $ac = $item['card_num'] > 0 ? round(100 * $item['active_num'] / $item['card_num'], 2) : 0;
                    $se = $item['card_num'] > 0 ? round(100 * $item['settle_num'] / $item['card_num'], 2) : 0;
                    $bstop = $item['wait_num'] > Statistics::DEFI_CARD_NUM ? true : false;
                    $respon[] = $this->setRed([
                        $item['seller_name'],
                        $item['concat'] . '【' . $item['concat_tel'] . '】',
                        $item['pid'] ? '二级商家' : '一级商家',
                        $item['card_num'],
                        $item['active_num'],
                        $item['wait_num'],
                        $item['wait_num'] > Statistics::DEFI_CARD_NUM ? '充足' : '不足',
                        $item['lsoe_num'],
                        $item['frost_num'],
                        $item['settle_num'],
                        $ac > 0 ? $ac . '%' : 0,
                        $se > 0 ? $se . '%' : 0,
                    ], $bstop);
                }
                if(!$this->seller->pid) {
                    $s_text = '合计发放数： <b class="font-red-mint">' . $total_card . '</b>；激活数： <b class="font-red-mint">' . $total_active . '</b>；激活率： ' .
                        '<b class="font-red-mint"> ' . ($total_ac > 0 ? $total_ac . '%' : 0) . '</b>；合计理赔数： <b class="font-red-mint">' . $total_settle . '</b>；理赔率： ' .
                        '<b class="font-red-mint"> ' . ($total_se > 0 ? $total_se . '%' : 0) . '</b>';
                }
            }
            return json_encode(array('data' => $respon, 'recordsTotal' => $total, 'recordsFiltered' => $total, 'statistics_text' => $s_text));
        }

        return $this->render('index',['level'=>$this->seller->pid]);

    }


    public function actionExport()
    {
        $get = Yii::$app->request->get();
        $model = $this->_condition([],$get);
        $data = $model->limit(5000)->all();

        foreach ($data as $item) {
            $ac = $item['card_num'] > 0 ? round(100 * $item['active_num'] / $item['card_num'], 2) : 0;
            $se = $item['card_num'] > 0 ? round(100 * $item['settle_num'] / $item['card_num'], 2) : 0;
            $respon[] = [
                $item['seller_name'],
                $item['concat'] . '【' . $item['concat_tel'] . '】',
                $item['pid'] ? '二级商家' : '一级商家',
                $item['card_num'],
                $item['active_num'],
                $item['wait_num'],
                $item['wait_num'] > Statistics::DEFI_CARD_NUM ? '充足' : '不足',
                $item['lsoe_num'],
                $item['frost_num'],
                $item['settle_num'],
                $ac > 0 ? $ac . '%' : 0,
                $se > 0 ? $se . '%' : 0,
            ];
        }
        set_time_limit(0);
        $this->_export($respon);
    }


    private function _export($respon)
    {
        theCsv::export([
            'data' => $respon,
            'name' => "seller_salfInsurance_statistics_" . date('Y_m_d_H', time()) . ".csv",    // 自定义导出文件名称
            'header' => ['商家名称', '联系人【电话】', '商家等级',  '卡券总数', '已激活', '未激活', '库存状态', '失效', '冻结', '理赔', '激活率', '理赔率'],
            //'header' => ['卡券序列号','生成时间','险种','卡券状态','所属商家'],
        ]);
    }

    private function setRed($array_text = [], $bstop = true)
    {
        if (!is_array($array_text) || !$array_text) {
            return [];
        }
        if ($bstop) {
            return $array_text;
        }
        foreach ($array_text as &$val) {
            $val = '<span class="font-red-mint">' . $val . '</span>';
        }
        return $array_text;
    }

    private function _condition($condition = [], $request = [])
    {
        $s_tb = Seller::tableName();
        $tj_tb = Statistics::tableName();
        $query = new Query();
        $where = ['s.is_insurance' => 1];
        $subQuery = (new Query())->from($tj_tb)->orderBy('id desc');
        $query->select([
            's.seller_id', 's.seller_name', 's.concat', 's.concat_tel', 's.status', 's.pid',
            't.add_time', 't.card_num', 't.active_num', 't.settle_num', 't.lsoe_num', 't.frost_num', 't.wait_num'

        ])->from(['s' => $s_tb])->leftJoin(['t' => $subQuery], 's.seller_id=t.seller_id');
        $post = Yii::$app->request->post();
        if ($request) {
            $post = array_merge($post, $request);
        }
        $query->where(['not in', 's.seller_id', Seller::$lehuanxin]);
        if (isset($post['diff']) && in_array($post['diff'], [1, 2])) {
            if ($post['diff'] == 1) {
                $query->andWhere(['>', 't.wait_num', Statistics::DEFI_CARD_NUM]);
            } else {
                $query->andWhere(['<=', 't.wait_num', Statistics::DEFI_CARD_NUM]);
            }
        }
        if (isset($post['level']) && in_array($post['level'], [1, 2])) {
            if ($post['level'] == 1) {
                $where['s.pid'] = 0;
            } else {
                $query->andWhere(['<>', 's.pid', 0]);
            }
        }

        if (isset($post['keyword']) && $post['keyword']) {
            $query->andWhere(['or', 's.seller_name LIKE \'%' . $post['keyword'] . '%\'', 's.concat LIKE \'%' . $post['keyword'] . '%\'', 's.concat_tel LIKE \'%' . $post['keyword'] . '%\'']);
        }
        if($this->seller->pid){
            $query->andWhere(['s.seller_id'=>intval($this->seller->seller_id)]);
        }else{
            $query->andWhere(['or','s.seller_id = '.intval($this->seller->seller_id),'s.pid = '.intval($this->seller->seller_id)]);
        }
        $condition = array_merge($where, $condition);
        $query->andWhere($condition)->groupBy('s.seller_id')->orderBy('t.wait_num DESC,s.seller_id DESC');
        return $query;
    }


}

maintainer/views/overall/index.php
<?php
use yii\helpers\Html;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '商家保险销售整体统计';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="portlet light portlet-fit portlet-datatable bordered">
	<!--统计开始-->
	<div class="overview_card" style="display: none">
		<img  src="<?= Yii::getAlias('@metro') ?>/global/img/loading-spinner-grey.gif" alt="" class="loading col-md-offset-3">
		<span> &nbsp;&nbsp;Loading... </span>
	</div>
	<!--统计结束-->

	<div class="portlet-title">
		<div class="caption">
			<i class="icon-settings font-green"></i>
			<span class="caption-subject font-green sbold uppercase"> <?= Html::encode($this->title) ?> </span>
		</div>
		<div class="actions">
			<a attr-url="<?=Yii::$app->urlManager->createUrl('overall/export')?>"  id="order-download"
			   class="btn  blue  btn-sm ">
				<i class="fa fa-download"></i> 导出
			</a>
		</div>
	</div>
	<div class="col-md-12">

	</div>
    <div class="portlet-body">
        <div class="table-container">
            <form id="datatable_form">
                <div class="table-search text-right">
					<?php if(!$level): ?>
					<select
						class="table-group-action-input form-control form-filter input-inline  input-sm"
						 name="diff">
						<option value="">库存状态</option>
						<option value="1">充足</option>
						<option value="2">不足</option>
					</select>
					&nbsp;&nbsp;&nbsp;
					<select
						class="table-group-action-input form-control form-filter input-inline  input-sm"
						id="datatable_filter" name="level">
						<option value="">商家等级</option>
						<option value="1">自营</option>
						<option value="2">二级商家</option>
					</select>
					&nbsp;&nbsp;&nbsp;

                    <input type="text" size="30" id="datatable_search" name="keyword" class="input-md form-filter form-control input-inline" placeholder="请输入商家名称/联系人/联系电话进行查询"/>
                    <button class="btn btn-sm green filter-submit " type="button" id="datatable_submit">
                        <i class="fa fa-search"></i> 搜索
                    </button>
					<?php endif; ?>
                </div>

            <table class="table table-striped table-bordered table-hover table-checkable dataTable no-footer" id="datatable_list">
                <thead>
                <tr role="row" class="heading">
                    <th width="14%">商家名称</th>
                    <th width="15%">联系人【电话】</th>
                    <th width="7%">商家等级</th>
					<th width="7%">卡券总数</th>
                    <th width="6%">已激活</th>
                    <th width="6%">未激活</th>
                    <th width="6%">库存状态</th>
                    <th width="6%">失效</th>
                    <th width="6%">冻结</th>
                    <th width="6%">理赔</th>
                    <th width="6%">激活率</th>
                    <th width="6%">理赔率</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
			</form>
        </div>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function() {
        var url = '<?php echo Yii::$app->urlManager->createUrl(['overall/index'])?>';
        var req = {};
        EcommerceList.init(url,req,false,'','',showData);

		//条件导出下载
        $('#order-download').on('click',function(){
            var parm=$('#datatable_form').serialize();
			var href = $(this).attr('attr-url');
			href +='?'+parm;
			bootbox.confirm("确认导出当前条件下所有统计数据?&nbsp;", function(result) {
				if(result){
					window.open(href, "_blank")
				}
			});
        });
    });
	
	function showData(data) {
		var s_data = data.statistics_text;
		$('#datatable_form .bottom .st').remove();
		$('#datatable_form .bottom').append('<p class="text-right st" style="float: right">'+s_data+'</p>')
	}
</script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/amcharts/amcharts/amcharts.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/amcharts/amcharts/pie.js" type="text/javascript"></script>
<script type="text/javascript">
	$(function(){


	});
	function getOverview() {
		$.getJSON('<?= \yii\helpers\Url::to(['mcoupon/default/overview']) ?>', function (data) {
			$('.overview_card').css('display', 'none');
			if (data.code == 'no') {
				showToastr('warning', data.message);
				return;
			}
			$(".overview_card").replaceWith(data.data.text);

			var chart;
			var legend;
			var chartData  = data.data.data;

			// PIE CHART
			chart = new AmCharts.AmPieChart();
			chart.dataProvider = chartData;
			chart.titleField = "name";
			chart.valueField = "value";
			chart.outlineColor = "#FFFFFF";
			chart.outlineAlpha = 0.8;
			chart.outlineThickness = 2;
			chart.balloonText = "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>";
			// this makes the chart 3D
			chart.depth3D = 15;
			chart.angle = 30;
			// WRITE
			chart.write("chartdiv");


		});
	}





</script>