backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use backend\components\BaseController;
use common\models\AdminLog;
use common\models\Article;
use common\models\Bank;
use common\models\BrandModel;
use common\models\Member;
use common\models\MemberExtend;
use common\models\Msg;
use common\models\Seller;
use Yii;
use backend\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\helpers\FileHelper;

/**
 * Site controller
 */
class SiteController extends BaseController
{
	/**
	 * @inheritdoc
	 */
	public function behaviors()
	{
		return [];
	}

	/**
	 * @inheritdoc
	 */
	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	/**
	 * Displays homepage.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}
		$model = Msg::find();
		$model->where(['seller_id'=>0]);
		$count=$model->count();
		$pageSize=15;
		$page=Yii::$app->request->get('page',0);
		if($page < 1 ){
			$page =0;
		}
		$dataProvider = new ActiveDataProvider([
				'query' =>$model->orderBy('status asc')->limit($pageSize)->offset($pageSize*$page)->asArray(),
				'pagination' => [
						'pageSize' => $pageSize,
						'page' => $page,
						'totalCount' => $count
				]
		]);
		$result=$dataProvider->getModels();

		return $this->render('index',['result'=>$result,'page'=>$page,'total_page'=>ceil($count/$pageSize)]);
	}


	public function actionHandlemsg(){
		if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}

		if(Yii::$app->request->isAjax && Yii::$app->request->isPost){
			$id = Yii::$app->request->post('id','');
			if(!$id){
				return $this->getCheckNo('参数错误!');
			}
			$member_id = Yii::$app->user->identity->id;
			$model = Msg::findOne(['id'=>$id]);
			$model->status = 1 ;
			$model->read_id = $member_id;
			$model->read_time =time();
			if($model->save()){
				return $this->getCheckYes([],'操作成功!');
			}
			return $this->getCheckNo('操作失败!');
		}
	}

	/**
	 * Login action.
	 *
	 * @return string
	 */
	public function actionLogin()
	{
		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['site/index']);
		} else {
			$this->layout = 'login_layout';//未登录 布局
			return $this->render('login', [
				'model' => $model,
			]);
		}
	}

	public function actionLock()
	{
		if (Yii::$app->user->isGuest) {
			return $this->redirect(['site/login']);
		}
		AdminLog::LogOutLog();
		$this->layout = 'empty_layout';//已登录 空布局
		return $this->render('user_lock');
	}

	/**
	 * Logout action.
	 *
	 * @return string
	 */
	public function actionLogout()
	{	AdminLog::LogOutLog();
		Yii::$app->user->logout(true);
		return $this->goHome();
	}

	protected function parseFile($file)
	{
		$data = array();
		$handle = fopen($file, "rb");
		while (!feof($handle)) {
			usleep(100);
			$line = fgets($handle);
			$line = iconv('gbk', 'utf-8', $line);
			$line = explode(',',$line);
			$data[] = $line;
			unset($_temp);
			$_temp = null;
			usleep(20);
		}
		return $data;
	}
	protected function fileLog($name,$data)
	{
		FileHelper::createDirectory(Yii::getAlias('@runtime').'/import_log',0775);
		$data = is_array($data)?var_export($data,true):$data;
		file_put_contents(Yii::getAlias('@runtime').'/import_log/'.$name.'_'.date("Y-m-d").'.log',$data.PHP_EOL,FILE_APPEND);
	}

	/**
	 * 导入商家信息
	 *
	 * [0] => Array
	(
	商家编号[0] => 21
	公司[1] => 四川欢欣网络技术有限公司
	联系人[2] => 蒋军保险
	联系电话[3] => 18140043611
	用户编号[4] => 10134
	是否保险商户[5] => 1
	是否维修商户[6] => 1
	商家等级[7] => 10
	父级商家[8] => 0
	商家添加时间[9] => 1460426438
	商家名称[10] => 乐换新
	省[11] => 23
	市[12] => 385
	区[13] => 45056
	地址[14] => 四川 成都市 高新区
	详细[15] => 府城大道399号天府新谷5-1306
	银行[16] =>
	账户[17] =>
	卡号[18] =>
	用户名 member[19] => 蒋军保险
	密码[20] => e10adc3949ba59abbe56e057f20f883e
	登录电话[21] => 18140043611
	真名[22] =>
	注册时间[23] => 1460426438

	)
	**/
	private function actionImportsellerinfo()
	{
		set_time_limit(0);
		echo 'start';
		//echo Yii::getAlias('@runtime');
		$path = Yii::getAlias('@runtime');
		$file_name = 'seller_import_info.csv';
		$d = $this->parseFile($path.'/'.$file_name);
		return ;die;
		//print_r($d);
		foreach($d as $k=>$v){

			if(!$v || !$v[0]){
				continue;
			}

			//添加用户
			$t_member = new Member();
			$t_member->isNewRecord = true;
			$t_member->attributes = [
				'name'=>$v[22]?$v[22]:$v[19],
				'phone'=>$v[21],
				'passwd'=>$v[20],
			];
			//print_r($t_member->attributes);die;
			if($t_member->save(false)){
				// 用户扩展
				$member_extend=new MemberExtend();
				$member_extend->member_id=$t_member->member_id;
				$member_extend->register_time=$v[23];
				$member_extend->save(false);

				//商家信息

				$t_seller = new Seller();
				$t_seller->isNewRecord = true;
				$t_seller->attributes = [
					'seller_name'=> $v[10],
					'member_id'=>$t_member->member_id,
					'is_insurance'=>$v[5],
					'is_repair'=>$v[6],
					'pid'=>0,
					'province_id'=>$v[11],
					'city_id'=>$v[12],
					'area_id'=>$v[13],
					'area_info'=>$v[14],
					'detail_address'=>$v[15],
					'concat'=>$v[2],
					'concat_tel'=>$v[3],
					'status'=>1,
					'add_time'=>$v[9],
					'is_agreement'=>1
				];
				if($t_seller->save(false)){
					if($v[16] && $v[17] && $v[18]){
						$bank = new Bank();
						$bank->isNewRecord = true;
						$bank->attributes = [
							'member_id'=>$t_member->member_id,
							'brank_name'=>$v[16],
							'brank_account'=>$v[18],
							'account_holder'=>$v[17],
							'is_default'=>1,
							'add_time'=>$v[9]
						];
						$bank->save(false);
					}
				}else{
					$this->fileLog('fail_seller_insert',implode(',',$v));
				}


			}else{
				$this->fileLog('fail_user_insert',implode(',',$v));
			}

		}

		echo '#end';

	}

	/**
	 * 维修报价处理
	**/

	private function actionBaojia()
	{
		set_time_limit(0);
		echo 'start';
       return ;die;
		$path = Yii::getAlias('@runtime');
		$file_name = 'baojia.csv';
		$d = $this->parseFile($path.'/'.$file_name);
		foreach($d as $k=>$v){

			if(!$v || !$v[0]){
				continue;
			}
			$brand = trim($v[0]);//品牌
			$b_model = trim($v[1]);//型号
			$price = trim($v[2]);//报价
			$obj_brand = BrandModel::findOne(['model_name'=>$brand]);
			if(!$obj_brand){
				$this->fileLog('fail_baojia',implode(',',$v));
				continue;
			}
			$obj_model = BrandModel::findOne(['model_name'=>$b_model,'parent_id'=>$obj_brand['id']]);
			if(!$obj_model){
				$this->fileLog('fail_baojia_model',implode(',',$v));
				continue;
			}

			$sql = "INSERT INTO `fj_brand_offer` VALUES (null, '{$obj_brand['id']}', '{$obj_model['id']}', '0', '{$brand} {$b_model}', '{$price}', '{$price}', '5', '1', '2016-12-19 14:33:07');";

			$this->fileLog('ok_baojia_sql',$sql);

		}

		echo '#end';
	}

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\base\InvalidParamException;
use yii\helpers\Html;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
		return [];
       /* return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];*/
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {   echo '<pre>';
		echo Html::a('后台','http://admin.baoxian.com',['target'=>'_blank']);
		echo '<br/>';
		echo Html::a('商家','http://business.baoxian.com',['target'=>'_blank']);
		//var_dump(Yii::$app->basePath);die;
        //return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Thank you for contacting us. We will respond to you as soon as possible.');
            } else {
                Yii::$app->session->setFlash('error', 'There was an error sending email.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionSignup()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->getSession()->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->getSession()->setFlash('error', 'Sorry, we are unable to reset password for email provided.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->getSession()->setFlash('success', 'New password was saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

	function getCurl($url, array $vars = array(), $method = 'post')
	{
		$method = strtolower($method);
		if ($method == 'get' && !empty($vars)) {
			if (strpos($url, '?') === false)
				$url = $url . '?' . http_build_query($vars);
			else
				$url = $url . '&' . http_build_query($vars);
		}

		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, $url);
		curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
		curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

		if ($method == 'post') {
			curl_setopt($ch, CURLOPT_POST, 1);
			curl_setopt($ch, CURLOPT_POSTFIELDS, $vars);
		}
		$result = curl_exec($ch);
		if (!curl_errno($ch)) {
			$result = trim($result);
		} else {
			$result = '';
		}

		curl_close($ch);
		return $result;

	}

	public function actionTest()
	{
		if(!Yii::$app->request->isPost && !Yii::$app->request->isAjax){
			echo \GuzzleHttp\json_encode(['code'=>400,'info'=>'非法请求']);die;
		}
		//print_r($_FILES);
		//print_r($_REQUEST);die;
		$xmlstr = file_get_contents("php://input","rb");
		if(!$xmlstr){
			echo \GuzzleHttp\json_encode(['code'=>400,'info'=>'非法数据']);die;
		}
		$jpg = $xmlstr;
		//echo $xmlstr;die;
		$file = "file_".time().".jpg";
		$hand = fopen($file,"wb");
		fwrite($hand,$jpg);
		fclose($hand);
		echo \GuzzleHttp\json_encode(['code'=>200,'info'=>$file]);

	}
}

backend/views/site/error.php
<link href="<?= Yii::getAlias('@metro'); ?>/pages/css/error.min.css" rel="stylesheet" type="text/css" />
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li>
			<a href="<?= $_SERVER['HTTP_REFERER'] ?>"><?= ucfirst($this->context->id) ?>&nbsp;<?= ucfirst($this->context->action->id) ?></a>
			<i class="fa fa-circle"></i>
		</li>
		<li>
			<span>Error</span>
		</li>
	</ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"> <?= $name ?>
	<small></small>
</h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
	<div class="col-md-12 page-404">
		<div class="number font-green"> <?= $exception->statusCode?:$exception->getCode() ?> </div>
		<div class="details">
			<h3><?= $name ?></h3>
			<p> <?= nl2br(\yii\helpers\Html::encode($message)) ?></p>
			<p><a class="btn red" href="<?= \yii\helpers\Url::to(['site/index']) ?>"> Return home </a>. </p>
		</div>
	</div>
</div>

backend/views/site/index.php
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN VALIDATION STATES-->
        <div class="portlet light portlet-fit portlet-form bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-red"></i>
                    <span class="caption-subject font-red sbold uppercase">系统消息</span>
                </div>
                <div class="actions">
                    <div class="btn-group btn-group-devided" data-toggle="buttons">

                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN PORTLET-->

                        <div class="col-md-12">


                            <div class="scroller" style="height: 580px;" data-always-visible="1"
                                 data-rail-visible="0">
                                <ul class="feeds">
                                    <?php foreach ($result as $val):
                                        $color = ' font-green-sharp';
                                        $href = 'javascript:void(0)';

                                        switch ($val['type']) {
                                            case 'withdrawal' :
                                                $msg = '提现申请';
                                                $msg_color = 'font-green-jungle';
                                                $href = Yii::$app->urlManager->createUrl(['withdraw/index', 'order_id' => $val['m_order_id']]);
                                                break;
                                            case 'payment' :
                                                $msg = '提现到账';
                                                $msg_color = 'font-red-thunderbird';
                                                $href = Yii::$app->urlManager->createUrl(['withdraw/index', 'order_id' => $val['m_order_id']]);
                                                break;
                                            case 'assigned':
                                                $msg = '维修指派';
                                                $msg_color = 'font-purple-seance';
                                                $href = Yii::$app->urlManager->createUrl(['ordermainten/view', 'id' => $val['m_order_id']]);
                                                break;
                                            default :
                                                $msg = '';
                                                $msg_color = '';
                                        }
                                        if ($val['status']) {
                                            $href = 'javascript:void(0)';
                                            $color = 'font-grey-mint';
                                            $msg_color = 'font-grey-mint';
                                        }
                                        ?>
                                        <li class="row">
                                            <div class="col-sm-9">
                                                <?php if (!$val['status']): ?> <a href="javascript:void(0)"
                                                                                  onclick="handleMsg(<?= $val['id'] ?>,'<?= $href ?>')"><?php endif; ?>
                                                    <div class="col1">
                                                        <div class="cont">
                                                            <div class="cont-col1">
                                                                <?php if (!$val['status']): ?>
                                                                    <div class="label label-sm label-danger">
                                                                        <i class="fa fa-bell-o"></i>
                                                                    </div>
                                                                <?php endif; ?>
                                                            </div>

                                                            <div class="cont-col2">

                                                                <div class="desc ">
                                                                    &nbsp;&nbsp;
                                                                    <span class="<?= $msg_color ?>">
                                                                        [ <?= $msg ?> ]
                                                                    </span>
                                                                    &nbsp;&nbsp;&nbsp;&nbsp;
                                                                    <span class="<?= $color ?>">
                                                                        <?= $val['content'] ?>
                                                                    </span>
                                                                </div>

                                                            </div>

                                                        </div>
                                                    </div>
                                                    <?php if (!$val['status']): ?></a><?php endif; ?>
                                            </div>
                                            <div class="col-sm-3 text-right">

                                                <div
                                                    class="date ">
                                                    <span>
                                                        <?=\common\models\Seller::getSeller($val['send_id'])->seller_name?>
                                                    </span>
                                                     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    <span><?= date('Y-m-d H:i', $val['add_time']) ?></span>
                                                </div>

                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <!--END TABS-->


                            <div class="row">
                                <div class="col-md-12 text-right">

                                    <ul class="pager pull-right">
                                        <?php if($total_page > 1 && $page): ?>
                                            <li><a href="<?=Yii::$app->urlManager->createUrl(['site/index','page'=>$page-1])?>">上一页</a></li>
                                        <?php endif; ?>
                                        <?php if($total_page > $page  && $total_page > 1): ?>
                                            <li><a href="<?=Yii::$app->urlManager->createUrl(['site/index','page'=>$page+1])?>">下一页</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>

                            </div>
                        </div>

                        <!-- END PORTLET-->

                    </div>
                </div>
            </div>
        </div>
        <!-- END VALIDATION STATES-->
    </div>
</div>
<script type="text/javascript">

    function handleMsg(id,url){
        $.post('<?=Yii::$app->urlManager->createUrl('site/handlemsg')?>',{id:id,'_csrf-backend': $('meta[name="csrf-token"]').attr("content")},function(data){
            if (data.code == 'yes') {
                window.location.href = url;
            }
        })
    }

</script>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\bootstrap\ActiveForm;
$this->title = 'Login';
?>

<!-- BEGIN LOGIN FORM -->
	<?php $form = ActiveForm::begin(['id'=>'login-form','method'=>'post','options'=>['class'=>'login-form']]) ?>
	<h3 class="form-title font-green">保险管理中心</h3>
	<div class="alert alert-danger display-hide">
		<button class="close" data-close="alert"></button>
		<span> Enter any username and password. </span>
	</div>
	<div class="form-group">
		<!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
		<label class="control-label visible-ie8 visible-ie9">账号</label>
		<input class="form-control form-control-solid placeholder-no-fix" type="text" value="" autocomplete="off" placeholder="账号" name="LoginForm[username]" /> </div>
	<div class="form-group">
		<label class="control-label visible-ie8 visible-ie9">密码</label>
		<input class="form-control form-control-solid placeholder-no-fix" type="password" value="" autocomplete="off" placeholder="密码" name="LoginForm[password]" /> </div>
	<div class="form-actions">
		<button type="submit" class="btn green uppercase">登录</button>
		<label class="rememberme check">
			<input type="checkbox" name="LoginForm[remember]" value="1" checked />记住密码</label>
		<!--<a href="javascript:;" id="forget-password" class="forget-password">Forgot Password?</a>-->
	</div>
<?= $form->errorSummary($model,['class'=>'color-view bg-red-intense bg-font-red-intense bold uppercase']); ?>
<?php ActiveForm::end(); ?>
<!-- END LOGIN FORM -->

backend/views/site/user_lock.php
<!DOCTYPE html>
<!-- 
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.5
Version: 4.5.2
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->

<head>
	<meta charset="utf-8" />
	<title>Metronic | User Lock Screen 1</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- BEGIN GLOBAL MANDATORY STYLES -->
	<!--<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />-->
	<link href="<?= Yii::getAlias('@metro'); ?>/global/fonts/Open_Sans_400_300_600_700_subset_all.css" rel="stylesheet" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
	<!-- END GLOBAL MANDATORY STYLES -->
	<!-- BEGIN THEME GLOBAL STYLES -->
	<link href="<?= Yii::getAlias('@metro'); ?>/global/css/components-md.min.css" rel="stylesheet" id="style_components" type="text/css" />
	<link href="<?= Yii::getAlias('@metro'); ?>/global/css/plugins-md.min.css" rel="stylesheet" type="text/css" />
	<!-- END THEME GLOBAL STYLES -->
	<!-- BEGIN PAGE LEVEL STYLES -->
	<link href="<?= Yii::getAlias('@metro'); ?>/pages/css/lock.min.css" rel="stylesheet" type="text/css" />
	<!-- END PAGE LEVEL STYLES -->
	<!-- BEGIN THEME LAYOUT STYLES -->
	<!-- END THEME LAYOUT STYLES -->
	<link rel="shortcut icon" href="favicon.ico" /> </head>
<!-- END HEAD -->

<body class="">
<div class="page-lock">
	<div class="page-logo">
		<a class="brand" href="index.html">
			<img src="<?= Yii::getAlias('@metro'); ?>/pages/img/logo-big.png" alt="logo" /> </a>
	</div>
	<div class="page-body">
		<div class="lock-head"> 锁屏 </div>
		<div class="lock-body">
			<div class="pull-left lock-avatar-block">
				<img src="<?= Yii::getAlias('@metro'); ?>/pages/media/profile/photo3.jpg" class="lock-avatar"> </div>
			<form class="lock-form pull-left" action="<?= Yii::$app->urlManager->createUrl('site/login') ?>" method="post">
				<h4><?= Yii::$app->user->identity->username ?></h4>
				<div class="form-group">
					<input type="hidden" name="_csrf-backend" value="<?=Yii::$app->request->csrfToken?>">
					<input type="hidden" name="LoginForm[username]" value="<?= Yii::$app->user->identity->username ?>">
					<input type="hidden" name="LoginForm[remember]" value="1" />
					<input class="form-control placeholder-no-fix" type="password" autocomplete="off" placeholder="密码" name="LoginForm[password]" /> </div>
				<div class="form-actions">
					<button type="submit" class="btn red uppercase">登录</button>
				</div>
			</form>
		</div>
		<div class="lock-bottom">
			<a href="<?= Yii::$app->urlManager->createUrl('site/login') ?>">不是 <?= Yii::$app->user->identity->username ?>?</a>
			<?php Yii::$app->user->logout(); ?>
		</div>
	</div>
	<div class="page-footer-custom"> 2016 © 乐换新. Admin For Insurance. </div>
</div>
<!--[if lt IE 9]>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/respond.min.js"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/excanvas.min.js"></script>
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/jquery.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/js.cookie.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?= Yii::getAlias('@metro'); ?>/global/scripts/app.min.js" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?= Yii::getAlias('@metro'); ?>/pages/scripts/lock.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<!-- END THEME LAYOUT SCRIPTS -->
</body>

</html>