backend/controllers/CoverageController.php
<?php

namespace backend\controllers;

use backend\components\LoginedController;
use common\library\UploadFile;
use common\models\InsuranceCompany;
use common\models\InsuranceType;
use Yii;
use common\models\InsuranceCoverage;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CoverageController implements the CRUD actions for InsuranceCoverage model.
 */
class CoverageController extends LoginedController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all InsuranceCoverage models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model_company=InsuranceCompany::findAll(['status'=>1]);
        $model_type=InsuranceType::findAll(['status'=>1]);
        $company_id=Yii::$app->request->get('company_id','');
        $type_id=Yii::$app->request->get('type_id','');
        $data=['c_id'=>$company_id,'t_id'=>$type_id];
        return $this->render('index',['model_company'=>$model_company,'model_type'=>$model_type,'pramas'=>$data]);
    }


    /**
     * Creates a new InsuranceCoverage model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new InsuranceCoverage();
        $model_company=InsuranceCompany::findAll(['status'=>1]);
        $model_type=InsuranceType::findAll(['status'=>1]);
        $id=Yii::$app->request->get('id',null);
        $info=[];
        if($id){
            $info=$model->find()->where(['id'=>$id])->asArray()->one();
            $info=$this->viewData($info);
        }
        return $this->render('create',['model_company'=>$model_company,'model_type'=>$model_type,'info'=>$info]);
    }

    /**
     * 返回默认保险信息资料
     * @param $seller
     * @return array
     */
    private function viewData($company){
        $company=is_array($company)?$company: [];
        $temp=['company_id'=>'','type_id'=>'','coverage_name'=>'','period'=>'','official_price'=>'','cost_price'=>'','wholesale_price'=>'',
            'max_payment'=>'','coverage_code'=>'','id'=>'','image'=>'','is_more'=>0];
        return array_merge($temp,$company);
    }

    public function actionUpdate(){
        if(!Yii::$app->request->isPost){
            return $this->showMessage('非法访问控制器');
        }

        $post=Yii::$app->request->post();
        $id=Yii::$app->request->post('id',null);
        $model = new InsuranceCoverage();
        if(!is_null($id)){
            $model=InsuranceCoverage::findOne(['id'=>$post['id']]);
            //$old_type = $model->type_id;
            //$old_company =$model->company_id;
            if(!$model){
                return $this->getCheckNo('当前险种ID不存在');
            }
        }
		if($model->isNewRecord){
			list($company_id,$company,$sp)=explode(',',$post['company_name']);
			list($type_id,$type,$type_code)=explode(',',$post['type_name']);
			$model->company_id=$company_id;
			$model->type_id=$type_id;
			$model->type_name=$type;
			$model->company_name=$company;
			$model->period=$post['period'];
			$model->official_price=$post['official_price'];
			$model->coverage_code = $sp . str_pad($post['period'], 2, 0, STR_PAD_LEFT) . str_pad(intval($post['official_price']), 3, 0, STR_PAD_LEFT) . $type_code;
			$model->status=1;

		}

        if($post['image']){
            $model->image=$post['image'];
        }
        $model->is_more=(int)$post['is_more'];
        $model->coverage_name=$post['coverage_name'];
        $model->cost_price=$post['cost_price'];
        $model->wholesale_price=$post['wholesale_price'];
        $model->max_payment=$post['max_payment'];
		$model->add_time=time();
        $model->note=$post['note'];
        if($model->save()){
            if(is_null($id)){
                $this->_secCompany($company_id);
                $this->_secType($type_id);
            }
            return $this->getCheckYes([],'操作成功');
        }
        return $this->getCheckNo('操作失败');
    }

    private function _secCompany($company_id=0,$add='add'){
        $company_model=InsuranceCompany::findOne(['id'=>$company_id]);
        if($company_model){
            if($add =='add'){
                $company_model->insurance_number += 1;
            }else if($add =='mod'){
                $company_model->insurance_number -= 1;
            }
            $company_model->save();
        }
    }

    private function _secType($type_id=0,$add='add'){
        $type_model=InsuranceType::findOne(['id'=>$type_id]);
        if($type_model){
            if($add =='add'){
                $type_model->insurance_number +=1;
            }else if($add =='mod'){
                $type_model->insurance_number -=1;
            }
            $type_model->save();
        }
    }

    public function actionChange(){
        if(!Yii::$app->request->isAjax || !Yii::$app->request->isPost){
            return $this->getCheckNo('非法访问!');
        }
        $id =Yii::$app->request->post('id');
        $status=Yii::$app->request->post('status',null);
        if(!$id || is_null($status)){
            return $this->getCheckNo('参数错误!');
        }
        $company = InsuranceCoverage::findOne(['id'=>$id]);
        if($company){
            $company->status = (int) $status;
            if($company->save()){
                return $this->getCheckYes([],'操作成功!');
            }
        }
        return $this->getCheckNo('操作失败!');
    }


    public function actionGetdata()
    {

        $post=Yii::$app->request->post();
        $pageSize = Yii::$app->request->post('length', 10);
        $start = Yii::$app->request->post('start', 0);//偏移量
        $coverage=InsuranceCoverage::find();
        $tj=[];
        if(isset($post['company_id']) && $post['company_id']){
            $tj['company_id']=$post['company_id'];
        }
        if(isset($post['type_id']) && $post['type_id']){
            $tj['type_id']=$post['type_id'];
        }
        if(isset($post['status']) && $post['status']){
            $tj['status']=$post['status'] - 1 ;
        }
        if(isset($post['period']) && $post['period']){
            $tj['period']=$post['period'];
        }
        $coverage->where($tj);
        if(isset($post['coverage_code']) && $post['coverage_code']){
            $coverage->andWhere(['like','coverage_code',$post['coverage_code']]);
        }

        $count=$coverage->count('*');
        $dataProvider = new ActiveDataProvider([
            'query' =>$coverage->orderBy('id DESC')->limit($pageSize)->offset($start),
            'pagination' => [
                'pageSize' => $pageSize,
                'page' => intval($start / $pageSize),
                'totalCount' => $count
            ]
        ]);

        $member = $dataProvider->getModels();

        $data=[
            'draw'=>intval($_REQUEST['draw']),
            'recordsTotal'=>$count,
            'recordsFiltered'=>$count,
            'data'=>[]
        ];
        foreach($member as $key=>$val){
            $btn = $val->status?
                '<a class="btn red btn-xs btn-default " onClick="handleStatus('.$val->id.','. 0 .')"  href="javascript:;"><i class="fa fa-caret-right"></i> 冻结 </a>'
                :'<a class="btn blue btn-xs btn-default" onClick="handleStatus('.$val->id.','. 1 .')" href="javascript:;"><i class="fa fa-check"></i> 解除冻结 </a>';
            $btn .= '&nbsp;&nbsp;&nbsp;<a class="btn btn-xs btn-success" href="'.$this->createUrl(['coverage/create','id'=>$val->id]).'"><i class="fa fa-edit"></i>编辑</a>';
            $data['data'][]=array(
//                '<input type="checkbox" name="id[]" value="'.$val->id.'">',
                $val->id,
                $val->coverage_name,
                $val->coverage_code,
                $val->company_name,
                $val->cost_price,
                $val->official_price,
                $val->type_name,
                $val->period.'月',
                $val->max_payment,
                $val->add_time?date('Y-m-d',$val->add_time):'',
                $val->status?'<span class="label label-sm label-success">正常</span>':'<span class="label label-sm label-danger">冻结中</span>',
                $btn
            );
        }

        return json_encode($data);
    }



    public function actionUpload(){
        if($_FILES['image']['name']) {
            $upload = new UploadFile();
            $dir = 'uploads/coverage/';
            $upload->maxSize = 3145728;
            $upload->savePath = $dir;
            $upload->allowExts = array('jpg', 'gif', 'png', 'jpeg');
            if (!$upload->upload()) {// 上传错误提示错误信息
                $msg = $upload->getErrorMsg();
                return json_encode(array('status' => 0, 'msg' =>$msg));
            } else {// 上传成功 获取上传文件信息
                $info = $upload->getUploadFileInfo();
                return json_encode(array('status' => 1, 'msg' =>'','url'=>'/'.$info[0]['savepath'].$info[0]['savename']));
            }
        }
        return json_encode(array('status' => 0, 'msg' =>'失败'));
    }

    /**
     * Finds the InsuranceCoverage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return InsuranceCoverage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = InsuranceCoverage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/coverage/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\InsuranceCoverage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="insurance-coverage-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'company_id')->textInput() ?>

    <?= $form->field($model, 'company_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type_id')->textInput() ?>

    <?= $form->field($model, 'type_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'coverage_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'period')->textInput() ?>

    <?= $form->field($model, 'cost_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'official_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'wholesale_price')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'max_payment')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'coverage_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'is_more')->textInput() ?>

    <?= $form->field($model, 'is_delay')->textInput() ?>

    <?= $form->field($model, 'image')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'add_time')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/coverage/index.php
<?php
$this->title = '数据表格';
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="#">商品</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>保险商品</span>
        </li>
    </ul>

</div>
<h3 class="page-title"> 保险商品
    <small>保险商品列表管理</small>
</h3>
<div class="row">
    <div class="col-md-12">
        <div class="note note-danger">

                <p>• 呈现所有乐换新销售的保险险种</p>
                <p>• 添加完成后，保险公司、官方指导价、保险类型和保期不能进行修改</p>
                <p>• 保险险种编码为自动生成 </p>

        </div>
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-user font-dark"></i>
                    <span class="caption-subject font-dark sbold uppercase">保险列表</span>
                </div>
                <div class="actions">
                    <div class="btn-group " >
                        <a href="<?=Yii::$app->urlManager->createUrl(['coverage/create'])?>" class="btn  blue  btn-sm ">
                            <i class="fa fa-plus-square"></i>  新增保险</a>
                    </div>
                </div>
            </div>
            <div class="portlet-body">

                <div class="table-container">
                    <form id="datatable_form">
                        <div class="table-search text-right">
                            <select
                                class="table-group-action-input form-control form-filter input-inline  input-sm" name="company_id">
                                <option value="">保险公司</option>
                                <?php if($model_company):foreach($model_company as $val): ?>
                                    <option value="<?=$val->id?>"  <?=$val->id ==$pramas['c_id']?'selected':''?>><?=$val->name?></option>
                                <?php endforeach;endif; ?>
                            </select>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <select
                                class="table-group-action-input form-control form-filter input-inline  input-sm" name="type_id">
                                <option value="">保险类型</option>
                                <?php if($model_type):foreach($model_type as $val): ?>
                                    <option value="<?=$val->id?>" <?=$val->id ==$pramas['t_id']?'selected':''?> ><?=$val->type_name?></option>
                                <?php endforeach;endif; ?>
                            </select>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <select
                                class="table-group-action-input form-control form-filter input-inline  input-sm" name="status">
                                <option value="">状态</option>
                                <option value="2">正常</option>
                                <option value="1">冻结中</option>
                            </select>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <select
                                class="table-group-action-input form-control form-filter input-inline  input-sm" name="period">
                                <option value="">保期</option>
                                <option value="1"> 1 月</option>
                                <option value="2"> 2 月</option>
                                <option value="3"> 3 月</option>
                                <option value="6"> 6 月</option>
                                <option value="12"> 12 月</option>
                                <option value="18"> 18 月</option>
                                <option value="24"> 24 月</option>
                            </select>
                            &nbsp;&nbsp;&nbsp;&nbsp;
                            <input type="text" size="30"  class="input-md form-filter form-control input-inline" name="coverage_code" placeholder="请输入保险险种进行查询"/>
                            <button class="btn btn-sm green filter-submit " type="button" id="datatable_submit">
                                <i class="fa fa-search"></i> 搜索
                            </button>
                        </div>
                    </form>
                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="datatable_ajax">
                        <thead>
                        <tr role="row" class="heading">
<!--                            <th width="2%">-->
<!--                                <input type="checkbox" class="group-checkable"></th>-->
                            <th width="5%"> ID&nbsp;#</th>
                            <th width="15%"> 保险名称</th>
                            <th width="8%"> 保险险种</th>
                            <th width="8%"> 保险公司</th>
                            <th width="7%"> 成本价</th>
                            <th width="7%"> 批发价</th>
                            <th width="8%"> 保险类型</th>
                            <th width="6%"> 保期</th>
                            <th width="7%"> 最高赔付</th>
                            <th width="9%"> 引入时间</th>
                            <th width="6%"> 状态</th>
                            <th width="18%"> 操作</th>
                        </tr>

                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
<script  type="text/javascript">
    $(function(){

        EcommerceList.init('/coverage/getdata',{},false,'datatable_ajax');
    });

    function handleStatus(id,status){
        App.blockUI();
        $.post('<?=Yii::$app->urlManager->createUrl(['coverage/change']);?>',{'_csrf-backend':$('meta[name="csrf-token"]').attr("content"),'id':id,'status':status},function(data){
            App.unblockUI();
            if(data.code !='yes'){
                showToastr('error',data.message);
                return false;
            }
            showToastr('success',data.message);
            setTimeout(function(){
                window.location.reload();
            },1000);
        });
    }
</script>

backend/views/coverage/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\InsuranceCoverage */

$this->title = 'Update Insurance Coverage: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Insurance Coverages', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="insurance-coverage-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/coverage/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\InsuranceCoverage */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Insurance Coverages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="insurance-coverage-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'company_id',
            'company_name',
            'type_id',
            'type_name',
            'coverage_name',
            'period',
            'cost_price',
            'official_price',
            'wholesale_price',
            'max_payment',
            'coverage_code',
            'status',
            'is_more',
            'is_delay',
            'image',
            'add_time:datetime',
        ],
    ]) ?>

</div>