backend/controllers/InsurancetypeController.php
<?php

namespace backend\controllers;

use backend\components\LoginedController;
use common\models\Article;
use Yii;
use common\models\InsuranceType;
use yii\data\ActiveDataProvider;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * InsuranceTypeController implements the CRUD actions for InsuranceType model.
 */
class InsurancetypeController extends LoginedController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all InsuranceType models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionGetdata()
    {

        $pageSize = Yii::$app->request->post('length', 10);
        $start = Yii::$app->request->post('start', 0);//偏移量
        $insurance_type=InsuranceType::find();
        $count=$insurance_type->count('*');
        $dataProvider = new ActiveDataProvider([
            'query' =>$insurance_type->orderBy('id desc')->limit($pageSize)->offset($start),
            'pagination' => [
                'pageSize' => $pageSize,
                'page' => intval($start / $pageSize),
                'totalCount' => $count
            ]
        ]);

        $member = $dataProvider->getModels();

        $data=[
            'draw'=>intval($_REQUEST['draw']),
            'recordsTotal'=>$count,
            'recordsFiltered'=>$count,
            'data'=>[]
        ];
        foreach($member as $key=>$val){
            $btn='<a class="btn green btn-xs btn-default" title="点击查看" data-target="#my-card-type" href="'.$this->createUrl(['insurancetype/view','type_id'=>$val->id]).'" data-toggle="modal"><i class="fa fa-share"></i>查看详细</a>';
            $btn .= $val->status?
                '<a class="btn red btn-xs btn-default " onClick="handleStatus('.$val->id.','. 0 .')"  href="javascript:;"><i class="fa fa-caret-right"></i> 冻结 </a>'
                :'<a class="btn btn-xs default btn-editable" onClick="handleStatus('.$val->id.','. 1 .')" href="javascript:;"><i class="fa fa-check"></i> 解除 </a>';

            $data['data'][]=array(
//                '<input type="checkbox" name="id[]" value="'.$val->id.'">',
                $val->id,
                $val->type_name,
                $val->type_code,
                '<a href="'.$this->createUrl(['coverage/index','type_id'=>$val->id]).'">'.$val->insurance_number.'</a>',
                $val->status?'<span class="font-green-sharp">正常</span>':'<span class="font-red-thunderbird">冻结</span>',
                $btn
            );
        }

        return json_encode($data);
    }




    public function actionChange(){
        if(!Yii::$app->request->isAjax || !Yii::$app->request->isPost){
            return $this->getCheckNo('非法访问!');
        }
        $seller_id =Yii::$app->request->post('id');
        $status=Yii::$app->request->post('status',null);
        if(!$seller_id || is_null($status)){
            return $this->getCheckNo('参数错误!');
        }
        $seller = InsuranceType::findOne(['id'=>$seller_id]);
        if($seller){
            $seller->status = (int) $status;
            if($seller->save()){
                return $this->getCheckYes([],'操作成功!');
            }
        }
        return $this->getCheckNo('操作失败!');
    }



    /**
     * Creates a new InsuranceType model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new InsuranceType();
        if(Yii::$app->request->isAjax && Yii::$app->request->isPost){
            $data=Yii::$app->request->post();
            $model->type_name=$data['type_name'];
            $model->type_code=$data['type_code'];
            $model->note=$data['note'];
            $model->created=time();
            if($model->save()){
                return $this->getCheckYes([],'新增成功');
            }

            return $this->getCheckNo('新增失败');
        }
        $code=$model->find()->orderBy('id desc')->one();
        $code_num=$code->type_code+1;
        return $this->render('create',['code'=>strlen($code_num) < 2?'0'.$code_num:$code_num]);
    }


    public function actionView(){
        $tid = Yii::$app->request->get('type_id','');
        if(!$tid){
            $this->showMessage('参数错误');
        }
        $info=InsuranceType::findOne(['id'=>$tid]);
        $article_info=Article::find()->select('tag_id,coverage_type_id,content')->where(['tag_id'=>[Article::COVEAGE_INFO,Article::COVEAGE_INSUE,Article::COVEAGE_CLAIMS],'status'=>1,'coverage_type_id'=>$tid])->asArray()->all();
        $view = ['info'=>'','claims'=>'','insure'=>''];
        if($article_info){
            foreach ($article_info as $val){
                if($val['tag_id'] == Article::COVEAGE_INFO){
                    $view['info'] = $val['content'];
                }elseif ($val['tag_id'] == Article::COVEAGE_INSUE){
                    $view['insure'] = $val['content'];
                }elseif ($val['tag_id'] == Article::COVEAGE_CLAIMS){
                    $view['claims'] = $val['content'];
                }
            }
        }
        return $this->renderPartial('view',['info'=>$info,'view'=>$view]);
    }


    /**
     * Finds the InsuranceType model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return InsuranceType the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = InsuranceType::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/insurancetype/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\InsuranceType */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="insurance-type-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'type_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'note')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'insurance_number')->textInput() ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'created')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/insurancetype/create.php
<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/select2/css/select2.min.css" rel="stylesheet"
      type="text/css"/>
<link href="<?= Yii::getAlias('@metro'); ?>/global/plugins/select2/css/select2-bootstrap.min.css" rel="stylesheet"
      type="text/css"/>

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="#">商品</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>保险类型</span>
        </li>
    </ul>

</div>
<h3 class="page-title"> 保险类型
    <small>新增类型</small>
</h3>
<div class="row">
    <div class="col-md-12">
        <div class="note note-danger">
            <p> 添加完成后，均不能再进行修改 .</p>
        </div>
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <form id="createInsuranceType" class="form-horizontal" method="post">
                <input type="hidden" name="_csrf-backend" value="<?= Yii::$app->request->csrfToken ?>">

                <div class="form-body">
                    <div class="alert alert-danger display-hide">
                        <button class="close" data-close="alert"></button>
                        您有一些错误,请检查您的输入
                    </div>
                    <div class="alert alert-success display-hide">
                        <button class="close" data-close="alert"></button>
                        验证成功!
                    </div>
                    <div class="form-group  margin-top-20">
                        <label class="control-label col-md-3">保险类型
                            <span class="required"> * </span>
                        </label>

                        <div class="col-md-4">
                            <div class="input-icon right">
                                <i class="fa"></i>
                                <input type="text" class="form-control" name="type_name" placeholder="保险类型"/></div>
                            <span class="help-block"> </span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">标识代码
                            <span class="required"> * </span>
                        </label>

                        <div class="col-md-4">
                            <div class="input-icon right">
                                <i class="fa"></i>
                                <input type="text" class="form-control" name="type_code" value="<?= $code ?>"/></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3">备注

                        </label>

                        <div class="col-md-4">
                            <div class="input-icon right">
                                <i class="fa"></i>
                                <textarea rows="4" class="form-control" name="note"></textarea>
                            </div>
                        </div>
                    </div>
                    <p></p>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" class="btn green">确定</button>
                            </div>
                        </div>
                    </div>
            </form>
            <p></p>
        </div>
    </div>
</div>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/select2/js/select2.full.min.js"
        type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/jquery-validation/js/jquery.validate.min.js"
        type="text/javascript"></script>
<script src="<?= Yii::getAlias('@metro'); ?>/global/plugins/jquery-validation/js/additional-methods.min.js"
        type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="<?= Yii::getAlias('@js'); ?>/validation-zh.js" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<script>
    $(function () {

        var form2 = $('#createInsuranceType');
        var error2 = $('.alert-danger', form2);
        var success2 = $('.alert-success', form2);

        form2.validate({
            errorElement: 'span',
            errorClass: 'help-block help-block-error',
            focusInvalid: false,
            ignore: "",
            rules: {
                type_name: {
                    required: true,
                    rangelength: [2, 25],
                },
                type_code: {
                    required: true,
                    number: true
                }
            },
            messages: {
                type_name: {
                    required: '请输入保险类型',
                    rangelength: '长度在于2到25位之间'
                },
                type_code: {
                    required: '请输入类型代码',
                    number: '请输入数字'
                }
            },

            invalidHandler: function (event, validator) {
//                success2.hide();
//                error2.show();
                showToastr('error','您有一些错误,请修正您的输入');
                App.scrollTo(error2, -200);
            },

            errorPlacement: function (error, element) {
                var icon = $(element).parent('.input-icon').children('i');
                icon.removeClass('fa-check').addClass("fa-warning");
                icon.attr("data-original-title", error.text()).tooltip({'container': 'body'});
                if (element.parents('.check_li').size() > 0) {
                    error.appendTo(element.parents('.check_li').attr("data-error-container"));
                } else {
                    error.insertAfter(element);
                }

            },

            highlight: function (element) {
                $(element)
                    .closest('.form-group').removeClass("has-success").addClass('has-error');
            },
            success: function (label, element) {
                var icon = $(element).parent('.input-icon').children('i');
                $(element).closest('.form-group').removeClass('has-error').addClass('has-success'); // set success class to the control group
                icon.removeClass("fa-warning").addClass("fa-check");
            },

            submitHandler: function (form) {
//
//                success2.show();
//                error2.hide();
                var form_data = $(form).serializeArray();
                App.blockUI();
                $.post('<?=Yii::$app->urlManager->createUrl(['insurancetype/create'])?>', form_data, function (data) {
                    App.unblockUI();
                    data = typeof data == 'string' ? $.parseJSON(data) : data;
                    if (data.code !== 'yes') {
                        showToastr('error', data.message);
                        return false;
                    }
                    showToastr('success', data.message);
                    setTimeout(function () {
                        window.location.href = '<?=Yii::$app->urlManager->createUrl(['insurancetype/index'])?>';
                    }, 2000);
                });
                return false;
            }
        });
    })


</script>

backend/views/insurancetype/index.php
<?php
$this->title = '数据表格';
?>
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="#">商品</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>保险类型</span>
        </li>
    </ul>

</div>
<h3 class="page-title"> 保险类型
    <small>保险类型列表管理</small>
</h3>
<div class="row">
    <div class="col-md-12">
        <div class="note note-danger">
            <p> 呈现所有乐换新销售的保险类型，识别代码为两位数字，作为保险险种代码所用 </p>
        </div>
        <!-- Begin: life time stats -->
        <div class="portlet light portlet-fit portlet-datatable bordered">
            <div class="portlet-title">
                <div class="caption">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject font-dark sbold uppercase">保险类型</span>
                </div>
                <div class="actions">
                    <div class="btn-group ">
                        <a href="<?= Yii::$app->urlManager->createUrl(['insurancetype/create']); ?>"
                           class="btn  blue   btn-sm ">
                            <i class="fa fa-plus-square"></i> 新增保险类型</a>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-actions-wrapper ">
                </div>
                <div class="table-container">

                    <table class="table table-striped table-bordered table-hover table-checkable"
                           id="datatable_ajax">
                        <thead>
                        <tr role="row" class="heading">
<!--                            <th width="2%">-->
<!--                                <input type="checkbox" class="group-checkable"></th>-->
                            <th width="5%"> ID&nbsp;#</th>
                            <th width="10%"> 保险类型</th>
                            <th width="10%"> 识别代码</th>
                            <th width="8%"> 已接入险种数</th>
                            <th width="8%"> 状态</th>
                            <th width="18%"> 操作</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- End: life time stats -->
    </div>
</div>
<!-- begin 协议 -->
<div class="modal fade bs-modal-lg" tabindex="-1" id="my-card-type" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <img src="<?= Yii::getAlias('@metro') ?>/global/img/loading-spinner-grey.gif" alt="" class="loading">
                <span> &nbsp;&nbsp;Loading... </span>
            </div>
        </div>
    </div>
</div>
<!-- end 协议 modal -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
<script type="text/javascript">
    $(function () {
        EcommerceList.init('<?=Yii::$app->urlManager->createUrl(['insurancetype/getdata']);?>', {}, false, 'datatable_ajax');
    });

    function handleStatus(id, status) {
        App.blockUI();
        $.post('<?=Yii::$app->urlManager->createUrl(['insurancetype/change']);?>', {
            '_csrf-backend': $('meta[name="csrf-token"]').attr("content"),
            'id': id,
            'status': status
        }, function (data) {
            App.unblockUI();
            if (data.code != 'yes') {
                showToastr('error', data.message);
                return false;
            }
            showToastr('success', data.message);
            setTimeout(function () {
                window.location.reload();
            }, 1000);
        });
    }
</script>

backend/views/insurancetype/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\InsuranceType */

$this->title = 'Update Insurance Type: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Insurance Types', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="insurance-type-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/insurancetype/view.php
<!--<div class="portlet light bordered">-->
<!--    <div class="portlet-title">-->
<!--        <div class="caption">-->
<!--            <i class="icon-social-dribbble font-purple-soft"></i>-->
<!--            <span class="caption-subject font-purple-soft bold uppercase">保险类型详情</span>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="portlet-body">-->
<!---->
<!--    </div>-->
<!--</div>-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
    <h4 class="modal-title">保险类型详情</h4>
</div>
<div class="modal-body">
    <div class="col-sm-12" style="margin-bottom: 30px">
        <h4><?=$info->type_name?><span class="font-purple-seance sbold">（code:#<?=$info->type_code?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;保险接入量：<?=$info->insurance_number?>）</span></h4>
        <p class="help-block" style="margin-top: 25px; color: #96c0d8">备注：<?=$info->note?></p>
    </div>
    <ul class="nav nav-tabs">
        <li class="active">
            <a href="#tab_1_1" data-toggle="tab"> 保险详情 </a>
        </li>
        <li>
            <a href="#tab_1_2" data-toggle="tab"> 投保须知 </a>
        </li>
        <li>
            <a href="#tab_1_3" data-toggle="tab"> 理赔须知 </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade active in" id="tab_1_1">
            <?=htmlspecialchars_decode($view['info'])?>
        </div>
        <div class="tab-pane fade" id="tab_1_2">
            <?=htmlspecialchars_decode($view['insure'])?>
        </div>
        <div class="tab-pane fade" id="tab_1_3">
            <?=htmlspecialchars_decode($view['claims'])?>
        </div>

    </div>
    <div class="clearfix margin-bottom-20"> </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn default" data-dismiss="modal">关闭</button>
    <!--<button type="button" class="btn blue">Save changes</button>-->
</div>